config/routes.rb
Rails.application.routes.draw do
  resources :repertoires do
    resources :songs
    post 'update_songs', to: 'songs#update_songs'
    resources :practice_sessions, only: :create
  end

  resources :instruments
  post 'update_instruments', to: 'instruments#update_instruments'
  resources :suggestions, only: [:show, :create]

  root 'repertoires#index'
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  validates :name, presence: true
  validates :key, presence: true
end

app/models/practice_session.rb
class PracticeSession < ActiveRecord::Base
  validate :repertoire_has_song

  belongs_to :repertoire
  has_many :songs, through: :repertoire
  has_many :suggestions

  def repertoire_has_song
    if repertoire.songs.none?
      errors.add :repertoire, 'must have at least one song to practice'
    end
  end
end

app/models/repertoire.rb
class Repertoire < ActiveRecord::Base
  validates :name, presence: true

  has_many :songs
  has_many :practice_sessions

  def selected_songs_count
    selected_songs = songs.where selected: true

    "(#{selected_songs.count} of #{songs.count} selected)"
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  validates :key, presence: true

  belongs_to :repertoire
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :practice_session

  before_save do
    self.song_id = select_song.id
    self.song_title = song.title
    self.key = select_key
    self.instrument_name = select_instrument_name
  end

  KEYS = %w(A Bb B C C#/Db D Eb E F F#/Gb G Ab)

  def songs
    practice_session.songs
  end

  def song
    Song.find(song_id)
  end

  def select_song
    songs.where(selected: true).sample
  end

  def select_key
    if song.comfort <=3
      song.key
    else
      KEYS.sample
    end
  end

  def select_instrument_name
    selected_instruments.map(&:name).sample
  end

  private

  def selected_instruments
    Instrument.where(selected: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :instrument, only: [:show, :edit, :update, :destroy]

  def index
    @instruments = Instrument.all
  end

  def show
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    if @instrument.save
      redirect_to instruments_path, notice: 'Instrument Added'
    else
      flash[:error] = 'Error Adding Instrument'
      render :new
    end
  end

  def edit
  end

  def update
    if @instrument.update(instrument_params)
      redirect_to @instrument, notice: 'Instrument Updated'
    else
      flash[:error] = 'Error Updating Instrument'
      render :edit
    end
  end

  def update_instruments
    Instrument.transaction do
      params[:instruments].each do |id, attributes|
        instrument = Instrument.find id
        instrument.update_attributes attributes.permit(:selected)
      end
      redirect_to instruments_path, notice: 'Selected Instruments Updated'
    end
  end

  def destroy
    @instrument.destroy
    redirect_to instruments_path, notice: 'Instrument Deleted'
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :key, :selected)
  end

  def instrument
    @instrument = Instrument.find(params[:id])
  end
end

app/controllers/practice_sessions_controller.rb
class PracticeSessionsController < ApplicationController
  def create
    repertoire = Repertoire.find(params[:repertoire_id])
    @practice_session = repertoire.practice_sessions.new

    if @practice_session.save
      Suggestion.transaction do
        suggestion = @practice_session.suggestions.create!
        redirect_to suggestion, status: :moved_permanently
      end
    else
      flash[:error] = 'Error Creating Practice Session'
      redirect_to repertoire, status: :moved_permanently
    end
  end
end

app/controllers/repertoires_controller.rb
class RepertoiresController < ApplicationController
  before_action :set_repertoire, only: [:show, :edit, :update, :destroy]

  def index
    @repertoires = Repertoire.all
  end

  def show
    @songs = @repertoire.songs.order(:title)
  end

  def new
    @repertoire = Repertoire.new
  end

  def create
    @repertoire = Repertoire.new(repertoire_params)
    if @repertoire.save
      redirect_to repertoires_path, notice: 'Repertoire Added'
    else
      flash[:error] = 'Error Creating Repertoire'
      render :new
    end
  end

  def edit
  end

  def update
    if @repertoire.update(repertoire_params)
      redirect_to @repertoire, notice: 'Repertoire Updated'
    else
      flash[:error] = "Error Updating Repertoire"
      render :edit
    end
  end

  def destroy
    @repertoire.destroy
    redirect_to root_path, notice: 'Repertoire Deleted'
  end

  private

  def repertoire_params
    params.require(:repertoire).permit(:name)
  end

  def set_repertoire
    @repertoire = Repertoire.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :repertoire
  before_action :song, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = @repertoire.songs.build(song_params)
    if @song.save
      redirect_to @repertoire, notice: 'Song Added'
    else
      flash[:error] = 'Error Creating Song'
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to repertoire_song_path(@repertoire, @song)
    else
      flash[:error] = 'Error Updating Song'
      render :edit
    end
  end

  def update_songs
    Song.transaction do
      params[:songs].each do |song_id, attributes|
        song = Song.find(song_id)
        song.update_attributes(attributes.permit(:selected))
      end
      redirect_to @repertoire, notice: 'Selected Songs Updated'
    end
  end

  def destroy
    @song.destroy
    redirect_to @repertoire, notice: 'Song Deleted'
  end

  private

  def song_params
    params.require(:song).permit(:title, :key, :quality, :comfort)
  end

  def repertoire
    @repertoire = Repertoire.find(params[:repertoire_id])
  end

  def song
    @song = Song.find(params[:id])
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def show
    @suggestion = Suggestion.find(params[:id])
    @practice_session = @suggestion.practice_session
  end

  def create
    practice_session = PracticeSession.find(params[:practice_session_id])
    @suggestion = practice_session.suggestions.build
    if @suggestion.save
      redirect_to @suggestion
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repertoires_helper.rb
module RepertoiresHelper
end

app/views/instruments/_form.html.haml
- if @instrument.errors.any?
  #error_explanation
    %h2= "#{pluralize(@instrument.errors.count, 'error')} prohibited this instrument from being saved:"
    %ul
      - @instrument.errors.full_messages.each do |message|
        %li= message

= form_for @instrument do |f|
  = f.label :name
  = f.text_field :name

  = f.label :key
  = f.text_field :key

  = f.label :selected
  = f.check_box :selected

  = f.submit submit_text

app/views/instruments/edit.html.haml
%h4 Edit Instrument

= render partial: 'form', locals: {submit_text: 'Update Instrument'}

app/views/instruments/index.html.haml
%h2 Instruments

= link_to 'New Instrument', new_instrument_path

= form_tag update_instruments_path do
  - @instruments.each do |instrument|
    = fields_for 'instruments[]', instrument do |f|
      = f.check_box :selected
      = link_to instrument.name, instrument
    %br
  = submit_tag 'Update Selected Instruments'

app/views/instruments/new.html.haml
%h4 New Instrument

= render partial: 'form', locals: {submit_text: 'Add Instrument'}

app/views/instruments/show.html.haml
%h2= @instrument.name

= link_to 'Edit', edit_instrument_path(@instrument)
= button_to 'Delete', @instrument, method: :delete, data: {confirm: 'Are you sure?'}

%p
  %strong Key:
  = @instrument.key

%p
  %strong Selected:
  = @instrument.selected

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RepertoireApp
    = csrf_meta_tags
    = favicon_link_tag 'notes.ico'
  %body
    .nav-bar
      = link_to 'Repertoires', repertoires_path
      = link_to 'Instruments', instruments_path

    - flash.each do |key, value|
      %div{class: "alert alert-#{key}"}= value

    = yield

app/views/repertoires/_form.html.haml
- if @repertoire.errors.any?
  #error_explanation
    %h2= "#{pluralize(@repertoire.errors.count, 'error')} prohibited this repertoire from being saved:"
    %ul
      - @repertoire.errors.full_messages.each do |message|
        %li= message

= form_for @repertoire do |f|
  = f.label :name
  = f.text_field :name

  = f.submit submit_text

app/views/repertoires/edit.html.haml
%h2 Edit Repertoire

= render partial: 'form', locals: {submit_text: 'Update Repertoire'}

app/views/repertoires/index.html.haml
%h1 Welcome to the Repertoire App!

= link_to 'New Repertoire', new_repertoire_path

- @repertoires.each do |repertoire|
  %h4= link_to repertoire.name, repertoire

app/views/repertoires/new.html.haml
%h2 New Repertoire

= render partial: 'form', locals: {submit_text: 'Add Repertoire'}

app/views/repertoires/show.html.haml
%h2= @repertoire.name

= button_to 'Practice', repertoire_practice_sessions_path(@repertoire), method: :post

= link_to 'Edit', edit_repertoire_path(@repertoire)
= button_to 'Delete', @repertoire, method: :delete, data: {confirm: 'Are you Sure?'}
%br
= link_to 'New Song', new_repertoire_song_path(@repertoire)

%h4 Songs:
%em= @repertoire.selected_songs_count

= form_tag repertoire_update_songs_path(@repertoire) do
  - @songs.each do |song|
    = fields_for 'songs[]', song do |sf|
      = sf.check_box :selected
      = link_to song.title, repertoire_song_path(@repertoire, song)
      %br
  = submit_tag 'Update Selected Songs'

app/views/songs/_form.html.haml
- if @song.errors.any?
  #error_explanation
    %h2= "#{pluralize(@song.errors.count, 'error')} prohibited this song from being saved:"
    %ul
      - @song.errors.full_messages.each do |message|
        %li= message

= form_for [@repertoire, @song] do |f|
  = f.label :title
  = f.text_field :title

  = f.label :key
  = f.text_field :key

  = f.label :quality
  = f.select :quality, [:major, :minor]

  = f.label :comfort
  = f.select :comfort, [0, 1, 2, 3, 4, 5]

  = f.submit submit_text

app/views/songs/edit.html.haml
%h2 Edit Song

= render partial: 'form', locals: {submit_text: 'Update Song'}

app/views/songs/new.html.haml
%h2 New Song

= render partial: 'form', locals: {submit_text: 'Add Song'}

app/views/songs/show.html.haml
%h2= @song.title

%p
  %strong Key:
  = "#{@song.key} #{@song.quality}"

%p
  %strong Comfort:
  = @song.comfort

%br
= link_to 'Edit', edit_repertoire_song_path(@repertoire, @song)
= button_to 'Delete', repertoire_song_path(@repertoire, @song), method: :delete, data: {confirm: 'Are you sure?'}

app/views/suggestions/show.html.haml
%h2= "Practicing: #{@practice_session.repertoire.name}"

.suggestion
  %strong Play:
  %span.suggested-song-title= @suggestion.song_title
  %strong In:
  %span.suggested-key #{@suggestion.key} #{@suggestion.song.quality}
  %strong On:
  %span.suggested-instrument= @suggestion.instrument_name

= button_to 'Next', suggestions_path(@suggestion, practice_session_id: @practice_session.id), method: :post